server:
  host: "0.0.0.0"
  port: ${PORT}
  log_level: "${LOG_LEVEL}"
  api_prefix: '/api/v1'

database:
  url: "postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

logging:
  enable_file: ${LOG_ENABLE_FILE}
  log_dir: "logs"
  rotation: "1 week"
  retention: "1 month"

security_settings:
  token_expire_minutes: 60
  jwt_algorithm: "HS256"
  jwt_issuer: "ai-recipes"
  jwt_audience: "ai-recipes-user"
  secret: "${JWT_SECRET}"
  fake_password_hash: "$2b$12$JdHtJOlkPFwyxdjdygEzPOtYmdQF5/R5tHxw5Tq8pxjubyLqdIX5i"
  testing: ${TESTING_MODE}
  max_login_attempts: 5
  user_lockout_time: 1

redis:
  clients:
    default:
#      url: "redis://${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}"
      host: "${REDIS_HOST}"
      port: "${REDIS_PORT}"
      db: "${REDIS_DB}"
      password: "${REDIS_PASSWORD}"
      max_connections: 10
      socket_timeout: 5
      socket_connect_timeout: 5
      serializer: "json"


storage_clients:
  private_minio:
    type: "minio"
    params:
      endpoint: "${PRIVATE_STORAGE_ENDPOINT}"
      access_key: "${MINIO_ACCESS_KEY}"
      secret_key: "${MINIO_SECRET}"
      bucket_name: "${PRIVATE_STORAGE_BUCKET}"
      secure: ${PRIVATE_STORAGE_SECURE}

  public_cloud_storage:
    type: "minio"
    params:
      endpoint: "${PUBLIC_STORAGE_ENDPOINT}"
      access_key: "${MINIO_ACCESS_KEY}"
      secret_key: "${MINIO_SECRET}"
      bucket_name: "${PUBLIC_STORAGE_BUCKET}"
      secure: ${PUBLIC_STORAGE_SECURE}
      public_endpoint: "${PUBLIC_STORAGE_PUBLIC_ENDPOINT}"

storage_profiles:
  user_avatars:
    client: "public_cloud_storage"
    default_folder: "avatars/{user_id}"
    max_file_size_mb: 5
    allowed_file_types:
      - "image/jpeg"
      - "image/png"
      - "image/webp"

  secure_reports:
    client: "private_minio"
    default_folder: "secure/reports/{year}"
    allowed_file_types:
      - "application/pdf"
      - "application/zip"
      - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      - "application/vnd.ms-excel"
      - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

  recipe_images:
    client: "public_cloud_storage"
    default_folder: "recipes/{recipe_id}"
    max_file_size_mb: 5
    allowed_file_types:
      - "image/jpeg"
      - "image/png"
      - "image/webp"

  general_files:
    client: "public_cloud_storage"
    default_folder: "general/{year}/{month}"
    allowed_file_types:
      - "image/jpeg"
      - "image/png"
      - "image/gif"
      - "image/webp"
      - "image/svg+xml"
      - "application/pdf"
      - "text/plain"
      - "text/csv"
      - "application/msword"
      - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      - "application/vnd.ms-excel"
      - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      - "application/vnd.ms-powerpoint"
      - "application/vnd.openxmlformats-officedocument.presentationml.presentation"
      - "application/zip"
      - "application/x-rar-compressed"
      - "application/x-7z-compressed"
      - "audio/mpeg"
      - "audio/wav"
      - "video/mp4"
      - "video/quicktime"